---
title: "CodeBook"
output: html_notebook
---
subject
  the group of 30 volunteers who carried out the experiment
    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    20
    21
    22
    23
    24
    25
    26
    27
    28
    29
    30

activity
  the six activities that each person performed
 WALKING
 WALKING_UPSTAIRS
 WALKING_DOWNSTAIRS
 SITTING
 STANDING
 LAYING
 
Other features including: 
tbodyaccmeanx           
tbodyaccmeany           
tbodyaccmeanz"           
tbodyaccstdx"            
tbodyaccstdy"            
tbodyaccstdz"            
tgravityaccmeanx"        
tgravityaccmeany"        
tgravityaccmeanz"        
tgravityaccstdx"         
tgravityaccstdy"         
tgravityaccstdz"         
tbodyaccjerkmeanx"       
tbodyaccjerkmeany"       
tbodyaccjerkmeanz"       
tbodyaccjerkstdx"        
tbodyaccjerkstdy"        
tbodyaccjerkstdz"        
tbodygyromeanx"          
tbodygyromeany"          
tbodygyromeanz"          
tbodygyrostdx"           
tbodygyrostdy"           
tbodygyrostdz"           
tbodygyrojerkmeanx"      
tbodygyrojerkmeany"      
tbodygyrojerkmeanz"      
tbodygyrojerkstdx"       
tbodygyrojerkstdy"       
tbodygyrojerkstdz"       
tbodyaccmagmean"         
tbodyaccmagstd"          
tgravityaccmagmean"      
tgravityaccmagstd"       
tbodyaccjerkmagmean"     
tbodyaccjerkmagstd"      
tbodygyromagmean"        
tbodygyromagstd"         
tbodygyrojerkmagmean"    
tbodygyrojerkmagstd"     
fbodyaccmeanx"           
fbodyaccmeany"           
fbodyaccmeanz"           
fbodyaccstdx"            
fbodyaccstdy"            
fbodyaccstdz"            
fbodyaccmeanfreqx"       
fbodyaccmeanfreqy"       
fbodyaccmeanfreqz"       
fbodyaccjerkmeanx"       
fbodyaccjerkmeany"       
fbodyaccjerkmeanz"       
fbodyaccjerkstdx"        
fbodyaccjerkstdy"        
fbodyaccjerkstdz"        
fbodyaccjerkmeanfreqx"   
fbodyaccjerkmeanfreqy"   
fbodyaccjerkmeanfreqz"   
fbodygyromeanx"          
fbodygyromeany"          
fbodygyromeanz"          
fbodygyrostdx"           
fbodygyrostdy"           
fbodygyrostdz"           
fbodygyromeanfreqx"      
fbodygyromeanfreqy"      
fbodygyromeanfreqz"      
fbodyaccmagmean"         
fbodyaccmagstd"          
fbodyaccmagmeanfreq"     
fbodyaccjerkmagmean"     
fbodyaccjerkmagstd"      
fbodyaccjerkmagmeanfreq" 
fbodygyromagmean"        
fbodygyromagstd"         
fbodygyromagmeanfreq"    
fbodygyrojerkmagmean"    
fbodygyrojerkmagstd"     
fbodygyrojerkmagmeanfreq"

These features selected for this database come from the accelerometer and gyroscope 3-axial raw signals taccxyz and tgyroxyz. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tbodyaccxyz and tgravityaccxyz) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tbodyaccjerkxyz and tbodygyrojerkxyz). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tbodyaccmag, tgravityaccmag, tbodyaccjerkmag, tbodygyromag, tbodygyrojerkmag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fbodyaccxyz, fbodyaccjerkxyz, fbodygyroxyz, fbodyaccjerkmag, fbodygyromag, fbodygyrojerkmag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'xyz' is used to denote 3-axial signals in the X, Y and Z directions.

The set of variables that were estimated from these signals are: 

mean: Mean value
std: Standard deviation